### ISSUE TITLE
Windows Installation Instructions

### ISSUE THREAD

**Issue by ottoworld** [jmaliksi/jlohn-mladden#11]
Here's what I did to get the app working on windows. I already had python 3.7 and pip installed.

pip install each of the requirements in requirements.txt e.g. **pip install "aiohttp-sse-client==0.1.7"**
If pyaudio fails, install pipwin first **pip install pipwin**
then **pipwin install pyaudio**
If ujson fails, install VS C++ Build Tools (haven't tested this)

To run in cmd **python jlohn_madden.py**

**Comment by jmaliksi** [comment]
did `pip install -r requirements.txt` not work?

**Comment by ottoworld** [comment]
No I just didn't realize that was an option oops. As long as it doesn't halt when one install fails, prob better to do it that way.

**Comment by jmaliksi** [comment]
perfect!
