### ISSUE TITLE
properly call balls - strikes as "and" instead of "dash"

### ISSUE THREAD

**Issue by ghost** [jmaliksi/jlohn-mladden#13]
when there's a call of the count of balls & strikes, we get "two dash one" instead of "two and one"

**Comment by jmaliksi** [comment]
so this is dependent on the localization for the specific voice. Some voices do it right by saying "three to one" or "three one", some voices don't.

I could do a blanket replace all dashes with spaces before feeding into the TTS, but I do like some of the localization specific stuff, ie the british voice localizes "3-0" to "three nil", but replacing with a space makes it go back to "three zero"

The other thought was adding specific localization overrides per voice, ie some of them are terrible at pronouncing "blaseball", "dalé", and "pies". This'll take a bit longer though, but I think is the "correct" way to do it

**Comment by jmaliksi** [comment]
this has been fixed for a while with `localizations`
