### ISSUE TITLE
Pronouncing lineage suffixes

### ISSUE THREAD

**Issue by SubstandardZeal** [jmaliksi/jlohn-mladden#19]
For players like [Parker MacMillan IIII](https://www.blaseball.com/player/f6d3c134-e3ee-40a1-bd4d-095347444129) with roman numeral lineage suffixes, Jlohn Mladden pronounces it as "eye eye eye eye" like other all-caps acronyms/etc.

**Comment by jmaliksi** [comment]
I heard that and it was really funny so I'm not fixing it lol.

If you have a local fork that you want it fixed in, open up `config/quips.yaml`, and add the following to `announcer.localization.global`:

```
-
  pattern: iiii
  replace: the fourth
```
